[build]
  command = "bash netlify_build.sh"
  publish = "staticfiles"
  functions = "netlify/functions"

[dev]
  command = "python manage.py runserver"
  port = 8000

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  PYTHON_VERSION = "3.8.12"
